### ISSUE TITLE
Build fails: Cannot read properties of undefined (reading 'check')

### ISSUE THREAD

**Issue by johnnydecimal** [delucis/astro-blog-full-text-rss#1]
I’m still troubleshooting, but I’ll drop this here in case anyone is better at it than me. Hint: you probably are.

Since upgrading from Astro 4.9 to 4.11, my build is failing on the processing of this file.

```txt
07:06:58 λ src/pages/rss.xml.ts
07:06:58   └─ /rss.xmlCannot read properties of undefined (reading 'check')
  Stack trace:
    at renderFrameworkComponent (file:///Users/john/dev/www.johnnydecimal.com/dist/chunks/astro/server_C3uKuhR1.mjs:1344:27)
```

Rudimentary logging tells me that the build gets as far as entering the `for (const { data, slug, collection } of posts)` loop at [line 32](https://github.com/delucis/astro-blog-full-text-rss/blob/latest/src/pages/rss.xml.ts#L32). So the call that’s failing is `await container.renderToString...`.

And honestly at this point I’m probably out of my depth. Sorry!

**Comment by johnnydecimal** [comment]
Update, a little more digging gets me closer to the issue.

Seems like [a call to](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/render/component.ts#L136)`r.ssr.check` fails.

```txt
file:///Users/john/dev/www.johnnydecimal.com/dist/chunks/astro/server_C3uKuhR1.mjs:1344
          if (await r.ssr.check.call({ result }, Component, props, children)) {
                          ^

TypeError: Cannot read properties of undefined (reading 'check')
    at renderFrameworkComponent (file:///Users/john/dev/www.johnnydecimal.com/dist/chunks/astro/server_C3uKuhR1.mjs:1344:27)
    at async renderComponent (file:///Users/john/dev/www.johnnydecimal.com/dist/chunks/astro/server_C3uKuhR1.mjs:1627:10)
```

I just realised I’m putting this issue in entirely the wrong place. I’ll move it over to the Astro repo.

**Comment by delucis** [comment]
No problem, hope you get it figured out 😁

**Comment by delucis** [comment]
Btw, I fixed this same error by updating the renderer pattern here: https://github.com/delucis/astro-blog-full-text-rss/commit/67b285b546bd19fa23aa559faa413870c1c44a7b

**Comment by johnnydecimal** [comment]
Amazing, will try that out. Really appreciate it.
